version: '3.8'

services:

  eldoria-server:
    build: .
    container_name: eldoria-server
    ports:
    - "8080:8080"
    restart: unless-stopped
    environment:
    - ELDORIA_TARGET=http://localhost:3000
    - PORT=8080
